apiVersion: v1
kind: Service
metadata:
  name: databricks-service
spec:
  selector:
    app: databricks
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30036
  type: NodePort
